### ISSUE TITLE
can not configure pdf_converter workflow on Nextcloud 19

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/workflow_pdf_converter#168]
## Steps to reproduce
1. activate pdf_converter
2. settings / configure flow
3. add pdf Converter
4. select pdf as mime type

### Expected behaviour
save configuration should work

### Actual behaviour
message "The configuration is invalid"
No events are chosen

## PDF Converter app

**PDF Converter app version:** (see apps admin page: `/index.php/settings/apps`)
1.4
## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by blizzz** [comment]
could you give us a screenshot, when it fails to save?

**Comment by ferdiga** [comment]
Hi

thanks for looking into this


I'd like to convert pdf to ocr readable documents


best regards / beste Grüße
Ferdinand Gassauer

**Comment by rules76** [comment]
HI
I've the same issue (NC 19.0.3), see attached screenshot.
Thank you very much
Marco
![error1](https://user-images.githubusercontent.com/59656907/98651799-fc209080-233a-11eb-984d-07d770007631.JPG)

**Comment by blizzz** [comment]
![Screenshot_20210118_124647](https://user-images.githubusercontent.com/2184312/104911497-3b96d900-598b-11eb-9000-b2906de8f2d4.png)

^ select an event there

**Comment by rules76** [comment]
Ops.. I'm so sorry... 
It's working fine.
Thank you.
