### ISSUE TITLE
PDF ocr to RTF ODT ODS doc xls ppt like

### ISSUE THREAD

**Issue by GM-G** [nextcloud/workflow_pdf_converter#18]
Hi,

This is a feature request - hoping it is an appropriate place to ask.

As I assume many might wish to have, a proper hot-folder system that will convert PDF's into editable ODS / writer spreadsheet presentation documents interpreting the format at best and with OCR.

Basically the other way round and way more complex, but any attempt would be great.

Cheers,
GG

**Comment by blizzz** [comment]
This is out of scope for this app (therefore closing), but the mechanics are similar. You can try to achieve this with an external script and https://apps.nextcloud.com/apps/workflow_script.  

Perhaps https://apps.nextcloud.com/apps/ocr can be extended… at least it pulls in the required stack. I'd request the feature there.
