### ISSUE TITLE
Incomplete installation instructions 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/workflow_pdf_converter#20]
The instructions say "LibreOffice must be installed on the server and the binary must be either detectable by Nextcloud or specified in the config.php as preview_libreoffice_path (cf. the sample config)."

I know how to edit the /var/www/nextcloud/config/config.php file but have no idea what the instruction means. Should I add the exact word "preview_libreoffice_path" in that file or should I add the true libreoffice path?  How can I find that path? How should it be specified? Where should I put it in the config.php file? 

Further - with LibreOffice do you mean OnlyOffice? Are they identical?

**Comment by blizzz** [comment]
We ship a config.sample.php which contains all possible configuration keys and their defaults. For instance:

```php
'preview_libreoffice_path' => '/usr/bin/libreoffice',
```

You'd just copy that line to config.php and adjust the path. 

> Further - with LibreOffice do you mean OnlyOffice? Are they identical?

They are not identical. LibreOffice is meant.

**Comment by rollanders** [comment]
Sorry for the confusion between libreoffice,  onlyoffice, collabora and richdocuments. 
Is Collabora the same as Libreoffice? Eg if I have installed collabora does that mean I have Libreoffice?

**Comment by blizzz** [comment]
Sort of… however you need an executable on your system. Typically, you have Collabora Online in a docker container, that would not help. Check you distribution packages for "libreoffice"

**Comment by rollanders** [comment]
OK. I have collabora in docker. You mean I need to install Libreoffice on another server?

**Comment by blizzz** [comment]
correct
