### ISSUE TITLE
Text strings  in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/workflow_pdf_converter#247]
There are strings from `workflow_pdf_converter-main.js` in Transifex that should not appear for translation.

**Comment by Valdnet** [comment]
There are still text strings in Transifex.

**Comment by rakekniven** [comment]
Cannot confirm.

Please check again.

**Comment by rakekniven** [comment]
Not sure why the sync did not happen?

**Comment by Valdnet** [comment]
@blizzz Is there anything known why the Transifex bot did not remove the wrong texts for translation?

**Comment by Valdnet** [comment]
ping @blizzz
Urgent :grin:.

**Comment by rakekniven** [comment]
Not sure why the sync did not happen?

**Comment by nickvergessen** [comment]
The app is not in the transifex sync screen anymore, either it's a pagination issue or it was dropped by accident

**Comment by rakekniven** [comment]
Just had a look at

https://github.com/nextcloud/docker-ci/blob/master/translations/config.json

and it's history.

Cannot find any related commit and on 27th of january it has been synced.

**Comment by Valdnet** [comment]
@rakekniven @blizzz There are still 13 text strings that shouldn't be present  :grimacing:.

**Comment by rakekniven** [comment]
Still the same at Transifex:

<img width="652" alt="Bildschirmfoto 2021-02-17 um 13 46 35" src="https://user-images.githubusercontent.com/2069590/108206419-a8d29100-7126-11eb-8998-593579e5af58.png">

**Comment by nickvergessen** [comment]
@rullzer do you know how to setup transifex and can you check it for this app?
Seems to be missing somewhere, I can't find it on the page where we force sync from transifex, so I guess it's also missing from the nightly cron jobs

**Comment by MorrisJobke** [comment]
> @rullzer do you know how to setup transifex and can you check it for this app?
> Seems to be missing somewhere, I can't find it on the page where we force sync from transifex, so I guess it's also missing from the nightly cron jobs

It was missing in https://github.com/nextcloud/docker-ci/commit/581d0528a6ba2a8bc128ba2e6ffbcac58d8520b0 

See https://docs.nextcloud.com/server/21/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync for the documentation.

**Comment by MorrisJobke** [comment]
I also cherry-picked https://github.com/nextcloud/workflow_pdf_converter/commit/1bcbf9aeb8e4262c90f74588123b7b9c16f1b083 to all stable branches.

**Comment by MorrisJobke** [comment]
With the latest change it's solved now 👍 Thanks for the heads up on this one.
