### ISSUE TITLE
PDF Converter and 'could not copy "filename"'

### ISSUE THREAD

**Issue by manu-p** [nextcloud/workflow_pdf_converter#263]
## Steps to reproduce
1. Activate the PDF converter app
2. Copy a file (not move) to get a new copy

### Expected behaviour
The file gets copied without an error message.

### Actual behaviour
An error message is displayed: 'Could not copy "_filename_"'
And the file is copied! 

## PDF Converter app

**PDF Converter app version:**  1.5.1

## Nextcloud Log

The NC log file shows something like:
`{"reqId":"Ly0QOSLeTTDypcWmKNQc","level":4,"time":"2021-02-19T09:34:44+00:00","remoteAddr":"A.B.C.D","user":"Manuel","app":"webdav","method":"COPY","url":"/remote.php/dav/files/Manuel/Talk/Capture%20d%E2%80%99%C3%A9cran%20de%202020-11-23%2010-29-24.png","message":{"Exception":"Error","Message":"Call to a member function getPath() on array","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/workflowengine/lib/AppInfo/Application.php","line":101,"function":"onEvent","class":"OCA\\WorkflowPDFConverter\\Operation","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"OCA\\WorkflowEngine\\AppInfo\\{closure}","class":"OCA\\WorkflowEngine\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":86,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":72,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/HookConnector.php","line":212,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":110,"function":"postCopy","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":950,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":469,"function":"copy","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":134,"function":"copyInto","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":687,"function":"copy","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpCopy","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/workflow_pdf_converter/lib/Operation.php","Line":96,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0","version":"20.0.6.1"}`

In the end of this line, you can see something related to workflow_pdf_converter...

## WORKAROUND

==> Just disable the workflow_pdf_converter app and copies are done without this error message.

**Comment by rotdrop** [comment]
Could this be related to #449?
