### ISSUE TITLE
converted document not indexed  by fulltext search plugin

### ISSUE THREAD

**Issue by smeyer73** [nextcloud/workflow_pdf_converter#28]
1) upload a doc file
2) assign a tag to convert it to pdf (and preserve the original)
3) launch cron to start the *.doc to pdf conversion..
4) index your files:
sudo -u www-data php occ fulltextsearch:index --verbose

5) result:
the *.doc file is indexed
but the PDF is not indexed..

any idea ?

**Comment by blizzz** [comment]
@smeyer73 does it work if you do an `occ files:scan -vvv -- $userid` before step 4?

**Comment by smeyer73** [comment]
@blizz no changes, same situation... :(

**Comment by blizzz** [comment]
@daita do you have an idea? We're working with file view api. So all the file meta data should be present.

**Comment by daita** [comment]
does the generated PDF contains a text-layer ?

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
