### ISSUE TITLE
Handling of postCopy event missing in Operation.php, lines 84-87?

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/workflow_pdf_converter#449]
The postCopy event has the same semantics as the postRename event (?), at least this is my impression, so it should be handled here as well?

https://github.com/nextcloud/workflow_pdf_converter/blob/814ccb6739913900085bf3b29d0ae4f290bb9c42/lib/Operation.php#L84-L87

**Comment by blizzz** [comment]
merged in #453, thanks!
