### ISSUE TITLE
Use collabora online if richdocuments is installed

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/workflow_pdf_converter#7]
Collabora online offers downloading a pdf version of the document. It would be nice, if we could integrate with that one, if the richdocuments app is installed, so there is no need to have an additional installation of libreoffice.

cc @rullzer Do you have any idea if that is easy to achieve, since it is probably similar to the preview generation?

**Comment by rullzer** [comment]
I guess so. I can check :)

**Comment by rullzer** [comment]
There is an PDF endppint (basically the same as their preview endpoint) to convert to PDF. Would it make sense to then implement this in the richdocument app?

**Comment by blizzz** [comment]
> There is an PDF endppint (basically the same as their preview endpoint) to convert to PDF. Would it make sense to then implement this in the richdocument app?

Maybe bundling this too close with richdocuments is not necessary. First, it's a different purpose this app is providing. While of course it is possible having this under the same hood, it extends the Collabora connector about a different and additional use case that is not closely connected to it.

Keeping it separated allows for more flexibility too. Currently, this works with plain libreoffice packages right from the distribution, no CODE or similar needed. Secondly it is easy to add different backends, of which there are tones. Potentially Onlyoffice, too.

**Comment by rullzer** [comment]
of course the issue is that you'd need a binary call on all op your appservers avaialble.

**Comment by blizzz** [comment]
for those yes, but there is nothing that blocks us from calling richdocuments/LOOL, is there?

**Comment by rollanders** [comment]
@blizz "this works with plain libreoffice packages right from the distribution," Do you mean I can just install the Libreoffice package and link to the executable and that all? I do not have to use Libreoffice for any other purpuse in the NC installation?

**Comment by juliushaertl** [comment]
> Maybe bundling this too close with richdocuments is not necessary. First, it's a different purpose this app is providing. While of course it is possible having this under the same hood, it extends the Collabora connector about a different and additional use case that is not closely connected to it.

@LinneyS asked about that for onlyoffice as well. I think it would make sense then to just register a workflow operation in the onlyoffice/collabora app themselves, so this app is just for converting using the libreoffice binary. What do you think @blizzz

**Comment by rullzer** [comment]
@juliushaertl yes that is a good idea!

**Comment by blizzz** [comment]
@juliushaertl agreed, this makes sense.

**Comment by juliushaertl** [comment]
Let's close this then and track it in the other apps repos:
https://github.com/nextcloud/richdocuments/issues/767
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/202
