### ISSUE TITLE
Migrate to @nextcloud/ packages

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/workflow_pdf_converter#93]
Please migrate to new @nextcloud/vue library and associated packages

**Comment by blizzz** [comment]
What exactly should be migrated over there?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/workflow_pdf_converter/blob/7cd2c51651fe56d118f8b49e1424486a6dfc382a/package.json#L18
